"""empty message

Revision ID: 3f76ca868f80
Revises: 69582594820a
Create Date: 2019-05-14 11:53:53.845042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f76ca868f80'
down_revision = '69582594820a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'category')
    # ### end Alembic commands ###
